---
title: "thompson-kenneth-ADA-homework-2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## CHALLENGE 1

```{r movies}

library(tidyverse)
library(mosaic)

f <-"https://raw.githubusercontent.com/difiore/ADA-datasets/master/IMDB-movies.csv"
d <- read.csv(f)
e <- filter(d, startYear %in% 1920:1979 & runtimeMinutes <240) %>%
  mutate(decade = startYear - (startYear %% 10))

p <- ggplot(e, aes(runtimeMinutes)) + labs(x= "Movie Run Time") + geom_histogram() + facet_wrap( ~ decade)
p

results <- tibble(
  decade = unique(e$decade),
  mean = mean(runtimeMinutes ~ decade, data = e), 
  sd = sqrt(sum((runtimeMinutes - mean(runtimeMinutes~ decade, data = e))^2 ~ decade, data = e) / favstats(runtimeMinutes ~ decade, data = e)$n)
)
results

single_sample <- tibble(
  decade = c(1920,1930,1940,1950,1960,1970),
  mean = mean(runtimeMinutes ~ decade, data = sample_n(e, size = 100, replace = FALSE)),
  sd = sd(runtimeMinutes ~ decade, data = sample_n(e, size = 100, replace = FALSE))
) %>% 
  mutate(se = sd/sqrt(length(sd)))
single_sample
                        
comparison <- tibble(
  decade = single_sample$decade,
  mean.p = results$mean,
  se.p = results$sd/(sqrt(length(results$sd))),
  mean.ss = single_sample$mean,
  se.ss = single_sample$se
)
comparison

e_1920 <- NULL
e_1930 <- NULL
e_1940 <- NULL
e_1950 <- NULL
e_1960 <- NULL
e_1970 <- NULL

for (i in 1:10000){
  filter(e, decade == 1920)
  e_1920[[i]] <- sample(e$runtimeMinutes, size = 100, replace = F)
}
for (i in 1:10000){
  filter(e, decade == 1930)
  e_1930[[i]] <- sample(e$runtimeMinutes, size = 100, replace = F)
}
for (i in 1:10000){
  filter(e, decade == 1940)
  e_1940[[i]] <- sample(e$runtimeMinutes, size = 100, replace = F)
}
for (i in 1:10000){
  filter(e, decade == 1950)
  e_1950[[i]] <- sample(e$runtimeMinutes, size = 100, replace = F)
}
for (i in 1:10000){
  filter(e, decade == 1960)
  e_1960[[i]] <- sample(e$runtimeMinutes, size = 100, replace = F)
}
for (i in 1:10000){
  filter(e, decade == 1970)
  e_1970[[i]] <- sample(e$runtimeMinutes, size = 100, replace = F)
}

m_1920 <- NULL
sd_1920 <- NULL
m_1930 <- NULL
sd_1930 <- NULL
m_1940 <- NULL
sd_1940 <- NULL
m_1950 <- NULL
sd_1950 <- NULL
m_1960 <- NULL
sd_1960 <- NULL
m_1970 <- NULL
sd_1970 <- NULL

for (i in 1:10000) {
  m_1920[[i]] <- mean(e_1920[[i]])
  sd_1920[[i]] <- sd(e_1920[[i]])
  m_1930[[i]] <- mean(e_1930[[i]])
  sd_1930[[i]] <- sd(e_1930[[i]])
  m_1940[[i]] <- mean(e_1940[[i]])
  sd_1940[[i]] <- sd(e_1940[[i]])
  m_1950[[i]] <- mean(e_1950[[i]])
  sd_1950[[i]] <- sd(e_1950[[i]])
  m_1960[[i]] <- mean(e_1960[[i]])
  sd_1960[[i]] <- sd(e_1960[[i]])
  m_1970[[i]] <- mean(e_1970[[i]])
  sd_1970[[i]] <- sd(e_1970[[i]])
}
```

## Challenge 2

```{r titi monkeys}
library(cowplot)
l <- 18
(fewer_than_13 <- ppois(13, lambda = l))
(no_calls <- dpois(0, lambda = l))
(exactly_7 <- dpois(7, lambda = l))  
(over_20 <- ppois(20, lambda = l, lower.tail = F))
p1 <-
    plotDist(
      "pois",
      lambda = l,
      xlab = "x",
      ylab = "Pr(X=x",
      xlim = c(0, 40)
    )
(sim <- rpois(520, lambda = l))
p2 <- histogram(sim,
                 xlim(0,40))
plot_grid(p1, p2) 
```

#

## Challenge 3

``` {r zombies}
f <-"https://raw.githubusercontent.com/difiore/ADA-datasets/master/zombies.csv"
d <- read.csv(f)

pop_sd <- function(x) {
  sqrt(sum((x - mean(x))^2) / (length(x)))
}

d_avg_tibble <- tibble(
  avg_height = mean(d$height),
  sd_height = pop_sd(d$height),
  avg_weight = mean(d$weight),
  sd_weight = pop_sd(d$weight),
  avg_killed = mean(d$zombies_killed),
  sd_killed = pop_sd(d$zombies_killed),
  avg_edu = mean(d$years_of_education),
  sd_edu = pop_sd(d$years_of_education),
  avg_age = mean(d$age),
  sd_age = pop_sd(d$age)
)
d_avg_tibble

ggplot(d, aes(x = height, y = age)) + 
  geom_point()
ggplot(d, aes(x = height, y = age)) +
  geom_point()

histogram(d$height)
qqnorm(d$height, main = "QQ Plot- Height")
histogram(d$weight)
qqnorm(d$weight, main = "QQ Plot- Weight")
histogram(d$zombies_killed)
qqnorm(d$zombies_killed, main = "QQ Plot- Number of Zombies Killed")
histogram(d$years_of_education)
qqnorm(d$years_of_education, main = "QQ Plot - Years of Education")
histogram(d$age)
qqnorm(d$age, main = "QQ Plot- Age")

d_samp <- sample_n(d, size = 30, replace = FALSE)

d_avg_tibble_samp <- tibble(
  avg_height = mean(d_samp$height),
  sd_height = sd(d_samp$height),
  avg_weight = mean(d_samp$weight),
  sd_weight = sd(d_samp$weight),
  avg_killed = mean(d_samp$zombies_killed),
  sd_killed = sd(d_samp$zombies_killed),
  avg_edu = mean(d_samp$years_of_education),
  sd_edu = sd(d_samp$years_of_education),
  avg_age = mean(d_samp$age),
  sd_age = sd(d_samp$age)
)

s = 30
d_samp <- sample_n(d, size = s, replace = FALSE)

d_avg_tibble_samp <- tibble(
  avg_height = mean(d_samp$height),
  sd_height = sd(d_samp$height),
  avg_weight = mean(d_samp$weight),
  sd_weight = sd(d_samp$weight),
  avg_killed = mean(d_samp$zombies_killed),
  sd_killed = sd(d_samp$zombies_killed),
  avg_edu = mean(d_samp$years_of_education),
  sd_edu = sd(d_samp$years_of_education),
  avg_age = mean(d_samp$age),
  sd_age = sd(d_samp$age)
)

d_avg_tibble_samp <- mutate(d_avg_tibble_samp, se_height = sd_height / sqrt(s))
d_avg_tibble_samp <- mutate(d_avg_tibble_samp, se_weight = sd_weight / sqrt(s)) 
d_avg_tibble_samp <- mutate(d_avg_tibble_samp, se_killed = sd_killed / sqrt(s)) 
d_avg_tibble_samp <- mutate(d_avg_tibble_samp, se_edu = sd_edu / sqrt(s))
d_avg_tibble_samp <- mutate(d_avg_tibble_samp, se_age = sd_age / sqrt(s))

CI <- function(x, level = 0.95) {
  alpha <- 1 - level
  ci <- mean(x) + c(-1, 1) * qnorm(1 - (alpha / 2)) * sqrt(var(x) / length(x))
  return(ci)
}

CI(d_samp$height)
CI(d_samp$weight)
CI(d_samp$zombies_killed)
CI(d_samp$years_of_education)
CI(d_samp$age)

ninety_nine <- NULL
for (i in 1:99) {
  ninety_nine[[i]] <-  d_samp <- sample_n(d, size = s, replace = FALSE)
}  

mean(ninety_nine[[1]]$height)

m_sample_height <- NULL
sd_sample_height <- NULL
for (i in 1:99) {
  m_sample_height[[i]] <- mean(ninety_nine[[i]]$height)
}
for (i in 1:99) {
  sd_sample_height[[i]] <- sd(ninety_nine[[i]]$height)
}

histogram(m_sample_height)

```
